/* eslint-disable global-require */

module.exports = {
  rules: {
    'accessible-emoji': require('./rules/accessible-emoji'),
    'alt-text': require('./rules/alt-text'),
    'anchor-ambiguous-text': require('./rules/anchor-ambiguous-text'),
    'anchor-has-content': require('./rules/anchor-has-content'),
    'anchor-is-valid': require('./rules/anchor-is-valid'),
    'aria-activedescendant-has-tabindex': require('./rules/aria-activedescendant-has-tabindex'),
    'aria-props': require('./rules/aria-props'),
    'aria-proptypes': require('./rules/aria-proptypes'),
    'aria-role': require('./rules/aria-role'),
    'aria-unsupported-elements': require('./rules/aria-unsupported-elements'),
    'autocomplete-valid': require('./rules/autocomplete-valid'),
    'click-events-have-key-events': require('./rules/click-events-have-key-events'),
    'control-has-associated-label': require('./rules/control-has-associated-label'),
    'heading-has-content': require('./rules/heading-has-content'),
    'html-has-lang': require('./rules/html-has-lang'),
    'iframe-has-title': require('./rules/iframe-has-title'),
    'img-redundant-alt': require('./rules/img-redundant-alt'),
    'interactive-supports-focus': require('./rules/interactive-supports-focus'),
    'label-has-associated-control': require('./rules/label-has-associated-control'),
    'label-has-for': require('./rules/label-has-for'),
    lang: require('./rules/lang'),
    'media-has-caption': require('./rules/media-has-caption'),
    'mouse-events-have-key-events': require('./rules/mouse-events-have-key-events'),
    'no-access-key': require('./rules/no-access-key'),
    'no-autofocus': require('./rules/no-autofocus'),
    'no-distracting-elements': require('./rules/no-distracting-elements'),
    'no-interactive-element-to-noninteractive-role': require('./rules/no-interactive-element-to-noninteractive-role'),
    'no-interactive-element-without-id-classname': require('./rules/no-interactive-element-without-id-classname'),
    'no-noninteractive-element-interactions': require('./rules/no-noninteractive-element-interactions'),
    'no-noninteractive-element-to-interactive-role': require('./rules/no-noninteractive-element-to-interactive-role'),
    'no-noninteractive-tabindex': require('./rules/no-noninteractive-tabindex'),
    'no-onchange': require('./rules/no-onchange'),
    'no-redundant-roles': require('./rules/no-redundant-roles'),
    'no-static-element-interactions': require('./rules/no-static-element-interactions'),
    'prefer-tag-over-role': require('./rules/prefer-tag-over-role'),
    'role-has-required-aria-props': require('./rules/role-has-required-aria-props'),
    'role-supports-aria-props': require('./rules/role-supports-aria-props'),
    scope: require('./rules/scope'),
    'tabindex-no-positive': require('./rules/tabindex-no-positive'),
  },
  configs: {
    recommended: {
      plugins: [
        'jsx-a11y',
      ],
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
      },
      rules: {
        'mea/alt-text': 'error',
        'mea/anchor-ambiguous-text': 'off', // TODO: error
        'mea/anchor-has-content': 'error',
        'mea/anchor-is-valid': 'error',
        'mea/aria-activedescendant-has-tabindex': 'error',
        'mea/aria-props': 'error',
        'mea/aria-proptypes': 'error',
        'mea/aria-role': 'error',
        'mea/aria-unsupported-elements': 'error',
        'mea/autocomplete-valid': 'error',
        'mea/click-events-have-key-events': 'error',
        'mea/control-has-associated-label': ['off', {
          ignoreElements: [
            'audio',
            'canvas',
            'embed',
            'input',
            'textarea',
            'tr',
            'video',
          ],
          ignoreRoles: [
            'grid',
            'listbox',
            'menu',
            'menubar',
            'radiogroup',
            'row',
            'tablist',
            'toolbar',
            'tree',
            'treegrid',
          ],
          includeRoles: [
            'alert',
            'dialog',
          ],
        }],
        'mea/heading-has-content': 'error',
        'mea/html-has-lang': 'error',
        'mea/iframe-has-title': 'error',
        'mea/img-redundant-alt': 'error',
        'mea/interactive-supports-focus': [
          'error',
          {
            tabbable: [
              'button',
              'checkbox',
              'link',
              'searchbox',
              'spinbutton',
              'switch',
              'textbox',
            ],
          },
        ],
        'mea/label-has-associated-control': 'error',
        'mea/label-has-for': 'off',
        'mea/media-has-caption': 'error',
        'mea/mouse-events-have-key-events': 'error',
        'mea/no-access-key': 'error',
        'mea/no-autofocus': 'error',
        'mea/no-distracting-elements': 'error',
        'mea/no-interactive-element-without-id-classname': [
          'error',
        ],
        'mea/no-interactive-element-to-noninteractive-role': [
          'error',
          {
            tr: ['none', 'presentation'],
            canvas: ['img'],
          },
        ],
        'mea/no-noninteractive-element-interactions': [
          'error',
          {
            handlers: [
              'onClick',
              'onError',
              'onLoad',
              'onMouseDown',
              'onMouseUp',
              'onKeyPress',
              'onKeyDown',
              'onKeyUp',
            ],
            alert: ['onKeyUp', 'onKeyDown', 'onKeyPress'],
            body: ['onError', 'onLoad'],
            dialog: ['onKeyUp', 'onKeyDown', 'onKeyPress'],
            iframe: ['onError', 'onLoad'],
            img: ['onError', 'onLoad'],
          },
        ],
        'mea/no-noninteractive-element-to-interactive-role': [
          'error',
          {
            ul: [
              'listbox',
              'menu',
              'menubar',
              'radiogroup',
              'tablist',
              'tree',
              'treegrid',
            ],
            ol: [
              'listbox',
              'menu',
              'menubar',
              'radiogroup',
              'tablist',
              'tree',
              'treegrid',
            ],
            li: ['menuitem', 'option', 'row', 'tab', 'treeitem'],
            table: ['grid'],
            td: ['gridcell'],
            fieldset: ['radiogroup', 'presentation'],
          },
        ],
        'mea/no-noninteractive-tabindex': [
          'error',
          {
            tags: [],
            roles: ['tabpanel'],
            allowExpressionValues: true,
          },
        ],
        'mea/no-redundant-roles': 'error',
        'mea/no-static-element-interactions': [
          'error',
          {
            allowExpressionValues: true,
            handlers: [
              'onClick',
              'onMouseDown',
              'onMouseUp',
              'onKeyPress',
              'onKeyDown',
              'onKeyUp',
            ],
          },
        ],
        'mea/role-has-required-aria-props': 'error',
        'mea/role-supports-aria-props': 'error',
        'mea/scope': 'error',
        'mea/tabindex-no-positive': 'error',
      },
    },
    strict: {
      plugins: [
        'jsx-a11y',
      ],
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
      },
      rules: {
        'mea/alt-text': 'error',
        'mea/anchor-has-content': 'error',
        'mea/anchor-is-valid': 'error',
        'mea/aria-activedescendant-has-tabindex': 'error',
        'mea/aria-props': 'error',
        'mea/aria-proptypes': 'error',
        'mea/aria-role': 'error',
        'mea/aria-unsupported-elements': 'error',
        'mea/autocomplete-valid': 'error',
        'mea/click-events-have-key-events': 'error',
        'mea/control-has-associated-label': ['off', {
          ignoreElements: [
            'audio',
            'canvas',
            'embed',
            'input',
            'textarea',
            'tr',
            'video',
          ],
          ignoreRoles: [
            'grid',
            'listbox',
            'menu',
            'menubar',
            'radiogroup',
            'row',
            'tablist',
            'toolbar',
            'tree',
            'treegrid',
          ],
          includeRoles: [
            'alert',
            'dialog',
          ],
        }],
        'mea/heading-has-content': 'error',
        'mea/html-has-lang': 'error',
        'mea/iframe-has-title': 'error',
        'mea/img-redundant-alt': 'error',
        'mea/interactive-supports-focus': [
          'error',
          {
            tabbable: [
              'button',
              'checkbox',
              'link',
              'progressbar',
              'searchbox',
              'slider',
              'spinbutton',
              'switch',
              'textbox',
            ],
          },
        ],
        'mea/label-has-for': 'off',
        'mea/label-has-associated-control': 'error',
        'mea/media-has-caption': 'error',
        'mea/mouse-events-have-key-events': 'error',
        'mea/no-access-key': 'error',
        'mea/no-autofocus': 'error',
        'mea/no-distracting-elements': 'error',
        'mea/no-interactive-element-to-noninteractive-role': 'error',
        'mea/no-interactive-element-without-id-classname': 'error',
        'mea/no-noninteractive-element-interactions': [
          'error',
          {
            body: ['onError', 'onLoad'],
            iframe: ['onError', 'onLoad'],
            img: ['onError', 'onLoad'],
          },
        ],
        'mea/no-noninteractive-element-to-interactive-role': 'error',
        'mea/no-noninteractive-tabindex': 'error',
        'mea/no-redundant-roles': 'error',
        'mea/no-static-element-interactions': 'error',
        'mea/role-has-required-aria-props': 'error',
        'mea/role-supports-aria-props': 'error',
        'mea/scope': 'error',
        'mea/tabindex-no-positive': 'error',
      },
    },
  },
};
